---
title: "**Expedientes con pagos a proveedores**"
output: 
  flexdashboard::flex_dashboard:
        orientation: rows
        theme: lumen
        vertical_layout: scroll
        favicon: logo_sga_azul40pctn.png
        logo: logoMSAL35pctn.png
---
##prueba a ver cambio     jjj

```{r echo=F, warning=FALSE, message=FALSE}
#1-importo las tablas
library(R.utils)
#tabla.sabana<-loadObject("C:/Users/JRamirez/Documents/TRABAJO/aaaSUBSE/FacturasEnTramite/tablas/tabla.sabana.Rbin")
tabla.sabana<-loadObject("../tablas/tabla.sabana.Rbin")
#tabla.resumen<-loadObject("C:/Users/JRamirez/Documents/TRABAJO/aaaSUBSE/FacturasEnTramite/tablas/tabla.resumen.Rbin")
tabla.resumen<-loadObject("../tablas/tabla.resumen.Rbin")
```

<!-- Comentarios {.sidebar}  -->
<!-- =====================================    -->

<!-- ####Incluye -->
<!-- Expedientes con estado abierto que hayan ingresado por TAD, para todas las modalidades de compra y todas las fuentes de financiamiento. -->

<!-- ####Excluye -->
<!-- Expedientes con facturas que ya se hayan devengado. -->

<!-- ####Información en cada hoja del tablero -->

<!-- **1)Indicadores en hoja resumen** -->

<!-- -Importe total en ARS (los importes en moneda extranjera se convierten utilizando el tipo de cambio nación vendedor vigente al día de la fecha del reporte). -->

<!-- -Cantidad de expedientes: total de expedientes en tramitación -->

<!-- -Promedio días desde último pase: mediana de los días transcurridos entre el último movimiento y la fecha del informe.  -->

<!-- -Promedio días desde la caratulación: mediana de los días transcurridos entre la fecha de caratulación y la fecha del informe.  -->

<!-- -Importe y cantidad de expedientes por ubicación: las ubicaciones externas a la Secretaría de Gestión Administrativa se agrupan en la categoría "programa". -->

<!-- -Importe por sistema de origen: ordenes de compra, financiamiento internacional y legítimo abono -->

<!-- -Importe por proveedor -->

<!-- **2)Tabla resumen por repartición y usuario** -->

<!-- -Importes agrupados por repartición y usuario actual -->

<!-- **3)Listado completo de expedientes** -->

<!-- -Información desagregada sobre cada expediente en trámite -->


```{r}
library(tidyverse)
monto_total<-tabla.resumen %>%
  summarize(total=round(sum(as.numeric(tabla.resumen$`Monto total de las facturas en $`),na.rm=T)/1000000,0)) %>%
  mutate(total_final=format(total, big.mark = ".")) %>% 
  filter(`Repartición actual`=="DA#INC - Dirección de administración")
```

Indicadores 
=====================================

Row {data-height=115, data-width=25%}
-----------------------------------------------------------------------

### Importe pendiente de ejecución `r format(Sys.Date(), "%B %d, %Y")`

```{r fila11}
library(flexdashboard)
valueBox(paste("$ M ",monto_total$total_final,sep=""),
         icon="fa-money",col="info")
```
```{r}
total_facturas<-tabla.resumen %>%
  summarise(total=round(sum(as.numeric(tabla.resumen$`Cantidad de facturas`),na.rm=T))) %>%
  mutate(total_final=format(total, big.mark = ".")) %>% 
  filter(`Repartición actual`=="DA#INC - Dirección de administración")
```

### Cantidad total de expedientes de pago para procesar 
```{r fila12}
library(flexdashboard)
valueBox(total_facturas$total_final,
         icon="fa-pencil",col="#E68BFB")
#valueBox(sum(tabla.resumen$`Cantidad de facturas`),
#         icon="fa-pencil",col="#E68BFB")
```

### Promedio de días que un expediente no registra movimiento 
```{r fila13}
library(flexdashboard)
valueBox(round(median(as.numeric(tabla.sabana$`Días desde último pase`),na.rm = TRUE),1),
         icon="fa-calendar",col="#303F9F")
```

### Promedio de días desde inicio de trámite
```{r fila14}
library(flexdashboard)
valueBox(round(median(as.numeric(tabla.sabana$`Días desde la caratulación`))),
         icon="fa-calendar",col="red")
```

Row {data-width=450 data-height=400}
-----------------------------------------------------------------------
### 
```{r fila21}
library(plotly)
library(dplyr)
#grafico importes por ubicacion

tabla.ubicacion<-tabla.sabana %>% 
  group_by(`Ubicación actual`) %>% 
  summarise(Monto.en.pesos=sum(`Monto en $`, na.rm = T),
            cantidad.exp=n()) %>% 
  arrange(`Ubicación actual`)

#modifico el orden del factor ubicacion
tabla.ubicacion$`Ubicación actual`<-factor(
  as.factor(tabla.ubicacion$`Ubicación actual`),
  levels= c("Despacho","RRHH","CRD","Presupuesto","Programas","DGPFE", "Compras", "SGA","DAL","DGA", "Contabilidad"))

fig.ubicacion <- plot_ly(tabla.ubicacion, 
                         labels = ~`Ubicación actual`, 
                         values = ~Monto.en.pesos, type = 'pie')
fig.ubicacion <- fig.ubicacion %>% 
  layout(title = 'Importe según ubicación actual',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig.ubicacion
```

###
```{r fila22}
library(plotly)
#grafico por sistema de origen
tabla.gr.origen<-tabla.sabana %>% 
  group_by(`Sist. de origen`) %>% 
  summarise(Monto.en.pesos=sum(`Monto en $`, na.rm = T)) %>% 
  mutate(Porcentaje = round(100*Monto.en.pesos/sum(Monto.en.pesos),1))

colores <- c('rgb(96, 43, 120)','rgb(211,94,96)', 'rgb(128,133,133)', 'rgb(144,103,167)', 'rgb(171,104,87)', 'rgb(114,147,203)')
fig.origen <- plot_ly(tabla.gr.origen, 
               labels = ~`Sist. de origen`, values = ~Monto.en.pesos, type = 'pie',
               marker = list(colors = colores))
fig.origen <- fig.origen %>% layout(title = 'Importe según sistema de origen',
                                    xaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                 showticklabels = FALSE),
                                    yaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                 showticklabels = FALSE))
fig.origen

```

Row {data-width=570 data-height=410}
-----------------------------------------------------------------------

### 
```{r fila3}
library(plotly)
library(dplyr)

tabla.estado.exped<-tabla.sabana %>% 
  group_by(`Estado expediente`) %>% 
  summarise (`Promedio de días desde último pase`= (round(mean(`Días desde último pase`,na.rm = TRUE))) , 
             Expedientes=n()) %>% 
  arrange(-`Promedio de días desde último pase`) %>% 
  ungroup()

#grafico expedientes por ubicacion
exp.ubicacion <- plot_ly(as.data.frame(tabla.estado.exped), 
                         x = ~`Estado expediente`, y = ~Expedientes, 
                         type = 'bar',
                         marker = list(color = '#B03060',
                                       line = list(color = 'rgb(8,48,107)',
                                                   width = 1.5))) %>% 
  layout(title = "Cantidad de expedientes por Estado",
         xaxis = list(title = ""),
         yaxis = list(title = ""))

exp.ubicacion
```

###

```{r fila35}
tabla.estado.exped<-tabla.sabana %>% 
  group_by(`Estado expediente`) %>% 
  summarise (`Promedio de días desde último pase`= (round(mean(`Días desde último pase`,na.rm = TRUE))) , 
             Expedientes=n()) %>% 
  arrange(-`Promedio de días desde último pase`) %>% 
  ungroup()

library(DT)
#tabla de proveedores
datatable(tabla.estado.exped, 
          options = list(initComplete = 
                    JS("function(settings, json){",
                       "$(this.api().table().header()).css({'background-color': '#303F9F', 'color': '#fff'});",
                      "}"),
          scrollY =F,
          pageLength = 140, 
          autoWidth = TRUE,
          dom = 't'),
          caption = "Expedientes por estado",
          #filter = 'top',
          class = 'cell-border stripe',
          callback = JS("return table;"), rownames=F,
          escape = TRUE,
          style = "default", width = NULL, height = NULL, elementId = NULL,
          fillContainer = getOption("DT.fillContainer", NULL),
          autoHideNavigation = getOption("DT.autoHideNavigation", NULL),
          selection = c("multiple", "single", "none"), extensions = list(),
          plugins = NULL, editable = FALSE) %>%
    formatStyle("Expedientes",'text-align'="center") %>% 
    formatStyle("Promedio de días desde último pase",'text-align'="center")
```

Row {data-width=550 data-height=400}
-----------------------------------------------------------------------

###
```{r fila41}
library(dplyr)
#armo la tabla de proveedores
tabla.prov<-tabla.sabana %>% 
  group_by(`Razón social`) %>% 
  summarise(Importe =sum(`Monto en $`)) %>% 
  arrange(-Importe) %>% 
  mutate(pctn=round(100*Importe/sum(Importe, na.rm = T),2)) %>% 
  mutate(Proveedores= case_when(
    pctn>=5 ~ `Razón social`,
    pctn<5 ~ "Otros")) %>% 
  group_by(Proveedores) %>% 
  summarise(`Importe en $`=sum(Importe, na.rm = T), 
            Porcentaje=sum(pctn, na.rm = T)) %>% 
  arrange(-Porcentaje) %>% 
  filter(Porcentaje>0)

## para acortar nombres de proveedores y que entren gráficos
tabla.prov$Proveedores[tabla.prov$Proveedores == "ASOCIACION HL7 HEALTH LEVEL SALUD NIVEL 7 ARGENTINA"] <- "ASOC HL7 ARGENTINA"
tabla.prov$Proveedores[tabla.prov$Proveedores == "FABRICA DE ALIMENTOS SANTA CLARA SA"] <- "FAB ALIMENTOS SANTA CLARA SA"
tabla.prov$Proveedores[tabla.prov$Proveedores == "ANDREANI LOGÍSTICA SA"] <- "ANDREANI LOG SA"

tabla.prov.sort<-rbind(tabla.prov[-1,], tabla.prov[1,])
#tabla.prov.sort<-rbind(tabla.prov[-1,], tabla.prov[1,])
tabla.prov.sort$`Importe en $` <- format(tabla.prov.sort$`Importe en $`, big.mark = ".")

library(DT)
#tabla de proveedores
datatable(tabla.prov.sort, 
          options = list(initComplete = 
                    JS("function(settings, json){",
                       "$(this.api().table().header()).css({'background-color': '#303F9F', 'color': '#fff'});",
                      "}"),
          scrollY =F,
          pageLength = 140, 
          autoWidth = TRUE,
          dom = 't'),
          caption = "Proveedores con mayor importe de facturación",
          #filter = 'top',
          class = 'cell-border stripe',
          callback = JS("return table;"), rownames=F,
          escape = TRUE,
          style = "default", width = NULL, height = NULL, elementId = NULL,
          fillContainer = getOption("DT.fillContainer", NULL),
          autoHideNavigation = getOption("DT.autoHideNavigation", NULL),
          selection = c("multiple", "single", "none"), extensions = list(),
          plugins = NULL, editable = FALSE) %>%
    formatStyle("Importe en $",'text-align'="right") 
```
###
```{r fila42}

tabla.prov<-tabla.sabana %>% 
  group_by(`Razón social`) %>% 
  summarise(Importe =sum(`Monto en $`)) %>% 
  arrange(-Importe) %>% 
  mutate(pctn=round(100*Importe/sum(Importe, na.rm = T),2)) %>% 
  mutate(Proveedores= case_when(
    pctn>=5 ~ `Razón social`,
    pctn<5 ~ "Otros")) %>% 
  group_by(Proveedores) %>% 
  summarise(`Importe en $`=sum(Importe, na.rm = T), 
            Porcentaje=sum(pctn, na.rm = T)) %>% 
  arrange(-Porcentaje) %>% 
  filter(Porcentaje>0)

## para acortar nombres de proveedores y que entren gráficos
tabla.prov$Proveedores[tabla.prov$Proveedores == "ASOCIACION HL7 HEALTH LEVEL SALUD NIVEL 7 ARGENTINA"] <- "ASOC HL7 ARGENTINA"
#tabla.prov$Proveedores[tabla.prov$Proveedores == "FABRICA DE ALIMENTOS SANTA CLARA SA"] <- "FAB ALIMENTOS SANTA CLARA SA"
#tabla.prov$Proveedores[tabla.prov$Proveedores == "ANDREANI LOGÍSTICA SA"] <- "ANDREANI LOG SA"

tabla.prov.sort<-rbind(tabla.prov[-2,], tabla.prov[2,])

library(plotly)
#grafico importe por proveedores

imp.prov <- plot_ly(tabla.prov.sort, 
                    labels = ~ Proveedores, values = ~`Importe en $` , type = 'pie') %>% 
  #layout(legend= list(itemsizing='trace'))%>%
  layout(title = 'Importe por proveedores',
       legend = list(font = list(size = 10)),
       xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
       yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
imp.prov
```

```{r}
tabla.resumen_repa <- tabla.resumen %>%
  dplyr::group_by(`Repartición actual`) %>% 
  dplyr::summarise(`Cantidad de facturas`=sum(`Cantidad de facturas`),  
                   `Monto total de las facturas en $`=(round(sum(`Monto total de las facturas en $`))),
                   `Promedio de días desde el ultimo pase`=(round(mean(`Promedio de días desde el ultimo pase`)))) 

  tabla.resumen_repa <- tabla.resumen_repa %>% 
  mutate_if(is.character,as.factor)
```


Tabla resumen por repartición y usuario actual
===================================== 

-----------------------------------------------------------------------

###Para agrandar o achicar el tamaño presionar "ctrl +" o "ctrl -". La tabla permite ordenar los datos, hacer filtros para cada variable y buscar un texto particular en toda la tabla (usando el casillero 'search')
```{r}
#8-genero la tabla resumen por reparticion
#A)genero la tabla en dplyr

library(DT)
tabla.resumen_repa %>%
  select(1,2,4,3) %>%
  arrange(desc(`Monto total de las facturas en $`))%>%
  datatable(extensions = 'Buttons',
            options = list(initComplete = 
                             JS("function(settings, json){",
                                "$(this.api().table().header()).css({'background-color': '#303F9F', 'color': '#fff'});",
                                "}"),
                           dom = 'Blfrtip',
                           scrollY=F,
                           buttons = c('csv', 'excel', 'pdf'),
                           pageLength = 200,
                           autoWidth = TRUE,
                           lengthMenu = list(c(10,50,100,-1),
                                             c(10,50,100,"Todo"))),
                      caption = "Se puede exportar a formatos csv, pdf y xls, conservando los filtros aplicados",
            class = 'cell-border stripe',
            callback = JS("return table;"), 
            rownames=F,
            escape = TRUE,
            style = "default", 
            width = NULL, 
            height = NULL, 
            elementId = NULL,
            fillContainer = getOption("DT.fillContainer", NULL),
            autoHideNavigation = getOption("DT.autoHideNavigation", NULL),
            selection = c("multiple", "single", "none"), 
            plugins = NULL, editable = FALSE,
            filter = 'top'
            )%>% 
  formatStyle(
    'Monto total de las facturas en $',
    background = styleColorBar(tabla.resumen$`Monto total de las facturas en $`,'steelblue'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  ) %>% 
  formatStyle(
    'Cantidad de facturas',
    background = styleColorBar(tabla.resumen$`Cantidad de facturas`,'green'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  ) 
```

```{r}
#tabla.sabana$Monto<- format(tabla.sabana$Monto, big.mark = ".")
```

Listado completo de expedientes
=====================================   

-----------------------------------------------------------------------

###Para agrandar o achicar el tamaño presionar "ctrl +" o "ctrl -". La tabla permite ordenar los datos, hacer filtros para cada variable y buscar un texto particular en toda la tabla (usando el casillero 'search')
```{r echo=F}
  tabla.sabana <- tabla.sabana %>%
    ungroup() %>% 
    mutate_if(is.character,as.factor)

tabla.sabana[,3:(ncol(tabla.sabana))] %>% 
arrange(desc(`Días desde último pase`))%>%
datatable(extensions = 'Buttons', 
          options = list(initComplete = 
                           JS("function(settings, json){",
                              "$(this.api().table().header()).css({'background-color': '#303F9F', 'color': '#fff'});",
                              "}"),
                         scrollY=F,
                         dom = 'Blfrtip',
                         buttons = c('csv', 'excel', 'pdf'),
                         pageLength = 200, 
                         lengthMenu = list(c(100, 200, 500, -1),
                                           c(100, 200, 500,"Todo")),
                         autoWidth = TRUE),
          caption = "Se puede exportar a formatos csv, pdf y xls, conservando los filtros aplicados",
          filter = 'top',
          class = 'cell-border stripe',
          callback = JS("return table;"), 
          rownames=F,
          escape = TRUE,
          style = "default", width = NULL, height = NULL, elementId = NULL,
          fillContainer = getOption("DT.fillContainer", NULL),
          autoHideNavigation = getOption("DT.autoHideNavigation", NULL),
          selection = c("multiple", "single", "none"), 
          plugins = NULL, editable = FALSE) %>%
          formatStyle("Monto",'text-align'="right") 
```


